config/routes.rb
Rails.application.routes.draw do

  get 'legislators/show'

  root "home#index"

  get "/auth/twitter", as: :twitter_login
  get "/auth/twitter/callback", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/district.rb
class District < ApplicationRecord
end

app/models/legislator.rb
class Legislator < ApplicationRecord
  belongs_to :district

  def self.all_data
    raw_data = service.get_reps
    raw_data["objects"].map do |info|
      Legislator.create!(LegislatorData.new(info).formatted)
    end
  end

  private

    def self.service
      GovTrackService.new
    end

end

app/models/legislator_data.rb
class LegislatorData
  attr_reader :formatted

  def initialize(data)
    district_data = set_district(data)

    @formatted = {
      state:         data["state"],
      district_id:   District.find_by(district_number: district_data).id,
      role_type:     data["title_long"],
      name:          data["person"]["name"],
      first_name:    data["person"]["firstname"],
      last_name:     data["person"]["lastname"],
      twitter_id:    data["person"]["twitterid"]
    }
  end

  def set_district(data)
    if !data["district"]
      0
    else
      data["district"]
    end
  end

end

app/models/user.rb
class User < ApplicationRecord

  def self.from_omniauth(auth_info)
    where(uid: auth_info[:uid]).first_or_create do |new_user|
      new_user.uid                = auth_info.uid
      new_user.screen_name        = auth_info.extra.raw_info.screen_name
      new_user.token              = auth_info.credentials.token
      new_user.secret             = auth_info.credentials.secret
      new_user.provider           = auth_info.provider
      new_user.profile_image      = auth_info.info.image
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  private

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @legislators = Legislator.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
    end
    redirect_to root_path
  end

  def destroy
    session.destroy
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class="jumbotron text-center transparent">
  <h1 class="display-3">Colorado Repspeak</h1>

  <p class="lead">Explore Senator and Representative tweets for every district!</p>

  <div id="map" style='width: 1000px; height: 500px;'>
    <script>

  function initMap() {
    var marker0 = {lat: 39.7318, lng: -104.9825};
    var marker1 = {lat: 39.5977, lng: -105.0712};
    var marker2 = {lat: 40.0155, lng: -105.0998};
    var marker3 = {lat: 39.706604, lng:  -106.294604};
    var marker4 = {lat: 39.4276, lng: -103.9439};
    var marker5 = {lat: 39.0574, lng: -104.9038};
    var marker6 = {lat: 39.7403, lng: -104.8598};
    var marker7 = {lat: 39.7953, lng: -105.1025};


    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 8,
      center: marker1
    });

    var contentString0 = '<div id="content">'+
        '<div id="siteNotice">'+
        '</div>'+
        '<h1 id="firstHeading" class="firstHeading">Checkout their Tweets!</h1>'+
        '<div id="bodyContent">'+
        '<p><a href="https://twitter.com/RepDianaDeGette">'+
        '@RepDianaDeGette</a> <br>'+
        '<p><a href="https://twitter.com/SenCoryGardner">'+
        '@SenCoryGardner</a> <br>'+
        '<p><a href="https://twitter.com/SenBennetCO">'+
        '@SenBennetCO</a> <br>'+
        '<p><a href="https://twitter.com/RepDLamborn">'+
        '@RepDLamborn</a> <br>'+
        '<p><a href="https://twitter.com/RepPerlmutter">'+
        '@RepPerlmutter</a> <br>'+
        '<p><a href="https://twitter.com/RepMikeCoffman">'+
        '@RepMikeCoffman</a> <br>'+
        '<p><a href="https://twitter.com/jaredpolis">'+
        '@jaredpolis</a> <br>'+
        '<p><a href="https://twitter.com/RepTipton">'+
        '@RepTipton</a> <br>'+
        '<p><a href="https://twitter.com/RepTipton">'+
        '@RepTipton</a> <br>'+
        '<p><a href="https://twitter.com/RepKenBuck">'+
        '@RepKenBuck</a> </p>'+
        '</p>'+
        '</div>'+
        '</div>';

      var contentString1 = '<div id="content">'+
        '<div id="siteNotice">'+
        '</div>'+
        '<h1 id="firstHeading" class="firstHeading">Legislators</h1>'+
        '<div id="bodyContent">'+
        '<p>See Tweets for <a href="https://twitter.com/RepDianaDeGette">'+
        '@RepDianaDeGette</a> <br>'+
        '<p>See Tweets for <a href="https://twitter.com/SenCoryGardner">'+
        '@SenCoryGardner</a> <br>'+
        '<p>See Tweets for <a href="https://twitter.com/SenBennetCO">'+
        '@SenBennetCO</a> <br>'+
        '<p>See Tweets for <a href="https://twitter.com/RepDLamborn">'+
        '@RepDLamborn</a> <br>'+
        '<p>See Tweets for <a href="https://twitter.com/RepPerlmutter">'+
        '@RepPerlmutter</a> <br>'+
        '<p>See Tweets for <a href="https://twitter.com/RepMikeCoffman">'+
        '@RepMikeCoffman</a> <br>'+
        '<p>See Tweets for <a href="https://twitter.com/jaredpolis">'+
        '@jaredpolis</a> <br>'+
        '<p>See Tweets for <a href="https://twitter.com/RepTipton">'+
        '@RepTipton</a> <br>'+
        '<p>See Tweets for <a href="https://twitter.com/RepTipton">'+
        '@RepTipton</a> <br>'+
        '<p>See Tweets for <a href="https://twitter.com/RepKenBuck">'+
        '@RepKenBuck</a> </p>'+
        '</p>'+
        '</div>'+
        '</div>';


    var infowindow = new google.maps.InfoWindow({
      content: contentString0,
      maxWidth: 500
    });

    var marker0 = new google.maps.Marker({
      position: marker0,
      map: map,
      title: 'marker0'
    });
    marker0.addListener('click', function() {
      infowindow.open(map, marker0);
    });
    var marker1 = new google.maps.Marker({
      position: marker1,
      map: map,
      title: 'marker1'
    });
    marker1.addListener('click', function() {
      infowindow.open(map, marker1);
    });
    var marker2 = new google.maps.Marker({
      position: marker2,
      map: map,
      title: 'marker2'
    });
    marker2.addListener('click', function() {
      infowindow.open(map, marker2);
    });
    var marker3 = new google.maps.Marker({
      position: marker3,
      map: map,
      title: 'marker3'
    });
    marker3.addListener('click', function() {
      infowindow.open(map, marker3);
    });
    var marker4 = new google.maps.Marker({
      position: marker4,
      map: map,
      title: 'marker4'
    });
    marker4.addListener('click', function() {
      infowindow.open(map, marker4);
    });
    var marker5 = new google.maps.Marker({
      position: marker5,
      map: map,
      title: 'marker5'
    });
    marker5.addListener('click', function() {
      infowindow.open(map, marker5);
    });
    var marker6 = new google.maps.Marker({
      position: marker6,
      map: map,
      title: 'marker6'
    });
    marker6.addListener('click', function() {
      infowindow.open(map, marker6);
    });
    var marker7 = new google.maps.Marker({
      position: marker7,
      map: map,
      title: 'marker7'
    });
    marker7.addListener('click', function() {
      infowindow.open(map, marker7);
    });
    var marker8 = new google.maps.Marker({
      position: marker8,
      map: map,
      title: 'marker8'
    });
    marker8.addListener('click', function() {
      infowindow.open(map, marker8);
    });
  }
</script>

    <script src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['GOOGLE_MAP_API']%>&callback=initMap"
    async defer></script>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Repspeak</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <!-- <script src="http://api.tiles.mapbox.com/mapbox.js/v5/mapbox.js"></script>
      <link href="http://api.tiles.mapbox.com/mapbox.js/v5/mapbox.css" rel="stylesheet" /> -->
      <!-- <script src="//maps.google.com/maps/api/js?v=3.23&key=<%=ENV['GOOGLE_MAP_API']%>"></script> -->
      <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
      <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
    <%= javascript_include_tag 'application' %>
    <!-- <script src="https://cdn.jsdelivr.net/gmap3/7.0.0/gmap3.min.js"></script> -->
    <!-- <link href="../styles.css" rel="stylesheet"><script src="http://maps.google.com/maps/api/js"></script><script src="https://code.jquery.com/jquery-2.1.4.min.js"></script><script src="https://cdn.jsdelivr.net/gmap3/7.1.0/gmap3.min.js"></script></head> -->

    <style>
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
      #map {
        height: 100%;
      }
    </style>
  </head>

  <body>

  <%= render 'shared/nav' %>

  <div class="container">
   <div class="row">
     <div class="col-md-12">
       <%= yield %>
     </div>
   </div>
  </div>

  <!-- <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDxdBXbPazO-Tk9s3B17oHZ6MpW9abMTjo&callback=initMap"
 type="text/javascript"></script> -->
  </body>
</html>

app/views/legislators/show.html.erb
<h1>Legislators</h1>

<table>
  <tr>
    <th>State</th>
    <th>District Number</th>
    <th>Role</th>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Full Name</th>
    <th>Twitter Id</th>
  </tr>

  <% @legislators %>


</table>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-fixed-top">
  <div class="navbar-header">
    <ul class="nav navbar-nav navbar-right">
    <% if current_user %>
        <li><%= link_to "Log Out", logout_path, class:"btn btn-primary" %></li>
    <% else %>
        <li><%= link_to "Sign in with Twitter", twitter_login_path, class:"btn btn-primary btn-lg" %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/shared/_reps_table.erb
<div class="all_reps">

  <h1>Colorado Representatives</h1>

  <table>
    <tr>
      <th>Job Title</th>
      <th>Last Name</th>
      <th>First Name</th>
      <th>District</th>
      <th>State</th>
      <th>Twitter</th>
    </tr>

     <% @legislators.each do |legislator| %>
    <tr class="rep">
      <td><%= legislator.name %></td>
      <td><%= legislator.last_name %></td>
      <td><%= legislator.first_name %></td>
      <td><%= legislator.district.district_number %></td>
      <td><%= legislator.state %></td>
      <td><%= legislator.twitter_id %></td>
    </tr>

    <% end %>

  </table>
</div>